/**
 * Interactive first-run configuration.
 *
 * Writes `apps/web/.env.local` and `apps/worker/.env`. Doing it by hand works,
 * but the two files have to agree on `WORKER_SECRET` — and a mismatch shows up
 * much later as an opaque 401 when the worker tries to claim a job. Generating
 * both from one place removes that failure mode, along with the temptation to
 * pick a memorable secret.
 *
 *   pnpm setup
 */

import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createInterface, type Interface } from "node:readline/promises";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const WEB_ENV = join(root, "apps", "web", ".env.local");
const WORKER_ENV = join(root, "apps", "worker", ".env");

/* ------------------------------------------------------------- rendering */

export type SetupAnswers = {
  databaseUrl: string;
  claudeToken: string;
  blobToken: string;
  searchAtlasKey: string;
  magnificKey: string;
  appUrl: string;
};

export type RenderedEnv = { web: string; worker: string };

export function secret(bytes = 32): string {
  return randomBytes(bytes).toString("hex");
}

/**
 * Builds both env files from one set of answers.
 *
 * Pure, and separate from the prompting, so the property that actually matters
 * — one `WORKER_SECRET` shared by both files, and every other secret distinct —
 * is testable without driving a terminal.
 */
export function renderEnvFiles(answers: SetupAnswers): RenderedEnv {
  const workerSecret = secret();

  const web = `# Generated by \`pnpm setup\`. Not committed.

DATABASE_URL="${answers.databaseUrl}"
WORKER_SECRET="${workerSecret}"
BLOB_READ_WRITE_TOKEN="${answers.blobToken}"
CRON_SECRET="${secret(16)}"

AUTH_SECRET="${secret(32)}"
# Local development only — skips sign-in so Google OAuth is not needed to look
# around. Remove this before deploying anywhere public.
AUTH_DISABLED="true"

# Optional: powers the "Sync from Notion" button.
NOTION_TOKEN=""
NOTION_CLIENTS_DATABASE_ID="483dbcc6-4b34-459e-be34-57c1f70383a6"
`;

  const worker = `# Generated by \`pnpm setup\`. Not committed.

APP_URL="${answers.appUrl}"
# Must match WORKER_SECRET in apps/web/.env.local — that pairing is how the
# worker proves it may claim jobs.
WORKER_SECRET="${workerSecret}"
DATABASE_URL="${answers.databaseUrl}"

CLAUDE_CODE_OAUTH_TOKEN="${answers.claudeToken}"
CLAUDE_MODEL="claude-opus-5"
CLAUDE_FAST_MODEL="claude-sonnet-5"

SEARCHATLAS_API_KEY="${answers.searchAtlasKey}"

MAGNIFIC_API_KEY="${answers.magnificKey}"
# nano-banana-pro-flash is Nano Banana 2 and the best of the three, but also
# the dearest. Swap to flux-dev (~a twentieth the cost) if the bill bites.
MAGNIFIC_IMAGE_MODEL="nano-banana-pro-flash"

LOG_LEVEL="info"
`;

  return { web, worker };
}

/* ------------------------------------------------------------- prompting */

class InputClosedError extends Error {
  constructor() {
    super("stdin closed before setup finished");
  }
}

/**
 * Asks one question.
 *
 * `readline.question()` never settles once stdin has closed, which would let
 * the process drain its event loop and exit silently having written nothing —
 * the worst outcome for a setup script. Racing against `close` turns that into
 * a loud failure. The listener is removed either way, so repeated prompts do
 * not pile up handlers.
 */
async function ask(
  rl: Interface,
  question: string,
  options: { required?: boolean; note?: string } = {},
): Promise<string> {
  if (options.note) console.log(`\n  ${options.note}`);

  for (;;) {
    let onClose: (() => void) | undefined;

    const answer = await Promise.race([
      rl.question(`  ${question}\n  > `),
      new Promise<never>((_, reject) => {
        onClose = () => reject(new InputClosedError());
        rl.once("close", onClose);
      }),
    ]).finally(() => {
      if (onClose) rl.off("close", onClose);
    });

    const trimmed = answer.trim();
    if (trimmed || !options.required) return trimmed;
    console.log("  This one is required.");
  }
}

function write(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
  console.log(`  ✔ wrote ${path.replace(root, ".")}`);
}

async function main(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  try {
    console.log("\nSEO Article Generator — configuration\n");
    console.log(
      "  Writes apps/web/.env.local and apps/worker/.env.\n" +
        "  Press Enter to skip anything optional; you can fill it in later.\n",
    );

    const existing = [WEB_ENV, WORKER_ENV].filter(existsSync);
    if (existing.length > 0) {
      console.log("  These already exist:");
      for (const path of existing) console.log(`    ${path.replace(root, ".")}`);
      const answer = await ask(rl, "Overwrite them? (y/N)");
      if (!["y", "yes"].includes(answer.toLowerCase())) {
        console.log("\n  Nothing changed.\n");
        return;
      }
    }

    const answers: SetupAnswers = {
      databaseUrl: await ask(rl, "DATABASE_URL", {
        required: true,
        note:
          "Postgres connection string. On Neon or Supabase use the POOLED one —\n" +
          "  its hostname contains '-pooler'.",
      }),
      claudeToken: await ask(rl, "CLAUDE_CODE_OAUTH_TOKEN", {
        note:
          "Run `claude setup-token` in another terminal and paste the result.\n" +
          "  This is what bills your Claude subscription instead of API credits.\n" +
          "  Skip for now if you just want to browse the app.",
      }),
      blobToken: await ask(rl, "BLOB_READ_WRITE_TOKEN", {
        note:
          "From a Vercel Blob store (vercel.com → Storage → Create → Blob).\n" +
          "  Needed to upload brand photos and to save generated images.",
      }),
      searchAtlasKey: await ask(rl, "SEARCHATLAS_API_KEY", {
        note:
          "From SearchAtlas → Dashboard → API Settings. Without it, keyword runs\n" +
          "  still cluster and find content gaps but show no volume figures.",
      }),
      magnificKey: await ask(rl, "MAGNIFIC_API_KEY", {
        note:
          "From the Magnific dashboard. Without it, articles use only the photos\n" +
          "  you upload to a client's Brand Vault — no generated imagery.",
      }),
      appUrl:
        (await ask(rl, "APP_URL", {
          note:
            "Where the worker looks for jobs. Leave blank for local development.",
        })) || "http://localhost:3000",
    };

    const rendered = renderEnvFiles(answers);
    console.log("");
    write(WEB_ENV, rendered.web);
    write(WORKER_ENV, rendered.worker);

    console.log("\n  Next:\n");
    console.log("    pnpm db:push        create the tables");
    console.log("    pnpm dev            the app, on http://localhost:3000");
    console.log("    pnpm worker         in a second terminal\n");
    if (answers.searchAtlasKey) {
      console.log("    pnpm searchatlas:probe  find the keyword endpoints");
    }
    if (answers.magnificKey) {
      console.log("    pnpm magnific:probe     verify image generation works");
    }
    if (answers.searchAtlasKey || answers.magnificKey) console.log("");

    const missing = [
      !answers.claudeToken &&
        "CLAUDE_CODE_OAUTH_TOKEN — the worker cannot generate anything without it",
      !answers.blobToken &&
        "BLOB_READ_WRITE_TOKEN — image upload and saving will fail",
      !answers.searchAtlasKey &&
        "SEARCHATLAS_API_KEY — keyword runs will have no volume data",
      !answers.magnificKey &&
        "MAGNIFIC_API_KEY — articles will have no generated images",
    ].filter((line): line is string => Boolean(line));

    if (missing.length > 0) {
      console.log("  Still to fill in:\n");
      for (const line of missing) console.log(`    · ${line}`);
      console.log("");
    }
  } finally {
    rl.close();
  }
}

// Only run the prompts when invoked directly; importing this module for its
// renderer must not start a terminal session.
const invokedDirectly =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (invokedDirectly) {
  main().catch((error) => {
    if (error instanceof InputClosedError) {
      console.error(
        "\n  Setup needs an interactive terminal and did not get one, so nothing\n" +
          "  was written. Run `pnpm setup` directly in a terminal, or copy\n" +
          "  .env.example to apps/web/.env.local and apps/worker/.env by hand —\n" +
          "  making sure WORKER_SECRET is the same string in both.\n",
      );
    } else {
      console.error("\nSetup failed:", error);
    }
    process.exit(1);
  });
}
